[files]
ignore-files = true
ignore-hidden = false
extend-exclude = [
    ".git/", "docs"
]

[default]
extend-ignore-re = [
    # hardcoded ID in src/lib.rs:29
    '94U5AHQMKkV5txNJ17QPXWoh474PheGou6cNP2FEuL1d',
]
check-filename = true