[toolchain]
anchor_version = "0.30.1-ca7fcee6b8269b732b66536f72ff3fb48cf1b5f9"

[workspace]
members = [
  "programs/gateway",
  "programs/examples/connectedSPL"
]

[features]
resolution = true
skip-lint = false

[programs.localnet]
connected_spl = "8iUjRRhUCn8BjrvsWPfj8mguTe9L81ES4oAUApiF8JFC"
gateway = "ZETAjseVjuFsxdRxo6MmTCvqFwb3ZHUx56Co3vCmGis"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.test.ts"

[test.validator]
url = "https://api.devnet.solana.com"

# [test]
# startup_wait = 100000

# cp-swap program in devnet
[[test.validator.clone]]
address = "CPMDWBwJDtYax9qW7AyRuVC19Cc4L4Vcy4n2BHAbHkCW"

# cp-swap create_pool_fee_reveiver in devnet
[[test.validator.clone]]
address = "G11FKBRaAkHAKuLCgLM6K6NUc9rTjPAznRCjZifrTQe2"

# cp-swap ammConfig in devnet
[[test.validator.clone]]
address = "9zSzfkYy6awexsHvmggeH36pfVUdDGyCcwmjT3AQPBj6"

# tokens
[[test.validator.clone]]
address = "2VJeR4LcdCHCxYxjsbbhcbpH7GsvDLVTh44idzXGh9Th"

[[test.validator.clone]]
address = "DEVmSoaTsVJvc5NrcUDzaQuAdHnGZhnjDMP16Dd91GKU"

[[test.validator.clone]]
address = "13VMCHVV9tLwmkr4xgEeakiargyEQq4B2jCwPrJq6JsR"

[[test.validator.clone]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"

[[test.validator.clone]]
address = "3LGcEveuCPBgSHqe3iN9eX8x65BaCJeuPKT5PZfVYD7q"

[[test.validator.clone]]
address = "AYmKYwZkqyetC7QoZgSrHDvoXtXJ29bgCfL22ske4HYX"

[[test.validator.clone]]
address = "bHJq7h2ZykY35Qx4DwjZqGwGb2RGWBoVSbW9efomizt"

[[test.validator.clone]]
address = "Hh4Epj1k2FYn4tuh8pYDQSQPYQR6ZivSm6GfJahWrvgT"

[[test.validator.clone]]
address = "CRuXMqy7u31up9f2Qksy7me8fW34gBt3erHe6nEmjNSG"

[[test.validator.clone]]
address = "So11111111111111111111111111111111111111112"

[[test.validator.clone]]
address = "Gh9ZwEmdLJ8DscKNTkTqPbNwLNNBjuSzaG9Vp2KGtKJr"

[[test.validator.clone]]
address = "A9Seij5cnSeSbu7dADsb4kTU7esxPS8Z37r3U9JF4C4z"

[[test.validator.clone]]
address = "9AvBWUfhCf7yfHUW1zA493GNgsEzmvvdaTKDJpSHX32N"

[[test.validator.clone]]
address = "A84muQUPmkCnmY9JCZ7NL1KSRRsA3h641niSu4pGWyuS"

[[test.validator.clone]]
address = "3eCLdZ1cX5yC2127kTUMwyvqFwHQxoZ2XUQSc7cuC5Fk"

[[test.validator.clone]]
address = "7xDWXgaDLFcs2emPXs7uWKT17FXcMqeH5BtSAjTQnaht"

[[test.validator.clone]]
address = "Fwj7Nfm6KZSHLyLAgxx8Q7rvrYf9tKxxV7Nr1P6zZQqF"

[[test.validator.clone]]
address = "Awhvh7BrYUidk4j8EHLL5mKeiEjChP3wtao7kn8kmmBT"