[toolchain]
anchor_version = "0.31.1"
solana_version = "2.1.0"

[workspace]
members = [
  "programs/gateway",
  "programs/examples/connected",
  "programs/examples/connectedSPL"
]

[features]
resolution = true
skip-lint = false

[programs.localnet]
connected = "4xEw862A2SEwMjofPkUyd4NEekmVJKJsdHkK3UkAtDrc"
connected_spl = "8iUjRRhUCn8BjrvsWPfj8mguTe9L81ES4oAUApiF8JFC"
gateway = "ZETAjseVjuFsxdRxo6MmTCvqFwb3ZHUx56Co3vCmGis"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build-gateway-dev = "anchor build --program-name gateway -- --features dev"
build-gateway = "anchor build --program-name gateway"
build-gateway-dev-upgrade-test = "anchor build --program-name gateway -- --features dev --features upgrade-test && mv target/deploy/gateway.so target/deploy/gateway_upgrade.so"
build-examples = "anchor build --program-name connected && anchor build --program-name connected_spl"
