name: example-workflow
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  anchor-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/setup-anchor@v3.1
      - run: anchor test
        shell: bash