name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-anchor-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/anchor-test@v2