name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true

    - name: Install Solana CLI
      run: |
        sh -c "$(curl -sSfL https://release.solana.com/v1.18.15/install)"
        echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

    - name: Install Anchor
      run: |
        cargo install --git https://github.com/coral-xyz/anchor --tag v0.30.0 anchor-cli --locked

    - name: Generate new keygen
      run: solana-keygen new

    - name: Install yarn dependencies
      run: yarn install

    - name: Run Anchor build
      run: anchor build

    - name: Run Anchor tests
      run: anchor test