name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-anchor-test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: metadaoproject/anchor-test@v2
        with:
          anchor-version: '0.30.1'
          solana-cli-version: '1.18.15'
          node-version: 'v20.15.0'