name: test
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Install ${{ matrix.toolchain }}
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ matrix.toolchain }}
    - uses: metadaoproject/anchor-test@v2.1
      with: 
        anchor-version: '0.30.1'
        solana-cli-version: '1.18.18'
        node-version: '21.1.0'
  