name: test

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: '20.11.0'
      - name: Cache Solana CLI tools
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/solana/
            ~/.local/share/solana/
          key: solana-cli-${{ runner.os }}-build-2.1.21
      - name: Install Solana CLI tools
        run: sh -c "$(curl -sSfL https://release.anza.xyz/v2.1.21/install)"
        shell: bash
      - name: Update PATH
        run: echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH 
        shell: bash
      - name: Install Anchor CLI via Cargo
        run: cargo install --git https://github.com/coral-xyz/anchor --tag v0.31.1 anchor-cli

      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ./node_modules/
          key: node-modules-${{ runner.os }}-build-20.11.0

      - name: Install dependencies
        run: yarn
        shell: bash

      - name: Generate Solana keypair
        run: solana-keygen new --no-bip39-passphrase
        shell: bash

      - name: Patch Anchor.toml for runner
        run: sed -i 's:/user/:/runner/:' Anchor.toml
        shell: bash

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustc

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2

      - name: Run Anchor tests
        run: yarn anchor-test
        shell: bash
