name: test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: metaDAOproject/setup-anchor@v3.1
        with:
          anchor-version: "0.31.2"
          solana-cli-version: "2.1.13"
          node-version: "22.11.0"

      - name: Make a default keypair
        run: |
          solana-keygen new --no-bip39-passphrase

      - name: Run tests
        run: anchor test