name: Anchor Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      program:
        description: "Program to test (subfolder under programs/)"
        required: false
        default: "gateway"

jobs:
  test:
    uses: solana-developers/github-workflows/.github/workflows/test.yaml@v0.2.5
    with:
      program: ${{ github.event.inputs.program || 'gateway' }}
